name: Create and publish a package
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install and test
        run: |
          sudo apt-get install -y libudev-dev
          npm install
          npm test
  publish-package:
    runs-on: ubuntu-latest 
    needs: run-npm-test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@weezevent'
    - run: sudo apt-get install -y libudev-dev
    - run: npm install
    - run: npm publish
    env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}